Update terraform to 0.13.5 version
giantswarm/giantnetes-terraform pull request #427
Opened 2020-12-10 11:04 UTC by corest

Towards https://github.com/giantswarm/giantswarm/issues/12286

2020-12-10 22:34 UTC, corest commented
No dramatic changes.
Most of the updates are related to warning abut interpolated strings
Few changes regarding how 3rd party providers are managed now

2020-12-11 06:21 UTC, whites11 approved these changes

2020-12-11 07:30 UTC, kopiczko approved these changes

2020-12-11 09:43 UTC, calvix approved these changes

2020-12-11 10:31 UTC, merged

2020-12-11 10:33 UTC, mazzy89 requested changes
tiny question about pinning providers

2020-12-11 10:33 UTC, mazzy89 commented on modules/aws/vault/versions.tf
> +      source = "hashicorp/aws"
small thing: below we pin providers, here no. is this wanted? should we pin providers everywhere?

2020-12-11 10:34 UTC, mazzy89 commented
arrived too late 😇